Set-Variable -Name commands -Value @(
	# Options
	'-d',
	'--diff',
	'-a',
	'-add',
	'-g',
	'--goto',
	'-n',
	'--new-window',
	'-r',
	'--reuse-window',
	'-w',
	'--locale',
	'--user-data-dir',
	'-h',
	'--help',
	# Extensions Management
	'--extensions-dir',
	'--list-extensions',
	'--show-versions',
	'--category',
	'--install-extension',
	'--pre-release',
	'--uninstall-extension',
	'--enable-proposed-api',
	# Troubleshooting
	'-v',
	'--version',
	'--verbose',
	'--log',
	'-s',
	'--status',
	'--prof-startup',
	'--disable-extensions',
	'--sync',
	'--inspect-brk-extension',
	'--disable-gpu',
	'--max-memory',
	'--telemetry'
)
